# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "lexiguard-ai"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = false

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "lexiguard-stack"
s3_prefix = "lexiguard-stack"
image_repositories = []
parameter_overrides = "ResourcePrefix=\"sandbox\" BucketName=\"lexiguard-legal-data-ps-b402\" KnowledgeBaseId=\"TUGECFALFA\" KnowledgeBaseDataSourceId=\"\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
